"""init

Revision ID: ef5cde18114f
Revises:
Create Date: 2025-10-23 14:57:37.647287

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ef5cde18114f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activities",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["activities.id"], name=op.f("activities_parent_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("activities_pkey")),
    )
    op.create_index(op.f("activities_id_idx"), "activities", ["id"], unique=False)
    op.create_table(
        "buildings",
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("buildings_pkey")),
    )
    op.create_index(op.f("buildings_id_idx"), "buildings", ["id"], unique=False)
    op.create_table(
        "organisations",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("phone_number", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("building_id", sa.Integer(), nullable=False),
        sa.Column("activities_ids", sa.ARRAY(sa.Integer()), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["building"], ["buildings.id"], name=op.f("organisations_building_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("organisations_pkey")),
    )
    op.create_index(op.f("organisations_id_idx"), "organisations", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("organisations_id_idx"), table_name="organisations")
    op.drop_table("organisations")
    op.drop_index(op.f("buildings_id_idx"), table_name="buildings")
    op.drop_table("buildings")
    op.drop_index(op.f("activities_id_idx"), table_name="activities")
    op.drop_table("activities")
    # ### end Alembic commands ###
